select ascii('a')
select char(65)
select lower('PRAKash')
select upper('PRAKash')
select ltrim("    Prakash")
select rtrim("Prakash     ")
select reverse("prakash")
select left("Kanchpuram",5)
select right("kanchpuram",5)
select replace("queries",'e','i')
select length("prakash")
select substring("computer",1,2)
select concat("a","b")